name: main foodgram workflow

on:
  push:
    branches:
      - main

jobs:
  backend-tests:
    name: Backend tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install backend dependencies
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Checks PEP8 with Flake8
        run: |
          cd backend
          pip install flake8
          flake8 . --max-line-length=92

      - name: Checks Backend Tests
        run: |
          cd backend/foodgram
          python manage.py test

  docker-build:
    name: Check Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Check Backend Build
        run: docker build -t foodgram-backend-test ./backend

      - name: Check Frontend Build
        run: docker build -t foodgram-frontend-test ./frontend
